Fix mocking Previews
hub4j/github-api pull request #1015
Opened 2021-01-05 16:09 UTC by seregamorph

# Description
Make `org.kohsuke.github.Previews` enum public.

Reasoning: fail to Mockito mock classes like `GHPullRequest` with failure:
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.kohsuke.github.GHPullRequest.
Mockito can only mock non-private & non-final classes.
...
Caused by: java.lang.IllegalAccessError: tried to access class org.kohsuke.github.Previews from class com.sun.proxy.$Proxy16
```
It's a regression since 1.118, was fine in 1.117.

Classes like `GHPullRequest` are "read-only" by design, hence we need convenient way to instantiate it in tests. Obvious possible way is to parse json payload, but it may be too verbose for trivial unit-testing.

2021-01-05 16:10 UTC, seregamorph commented on src/test/java/org/kohsuke/github/GHPullRequestMockTest.java
> +        GHPullRequest pullRequest = mock(GHPullRequest.class);
this test will fail if you revert change in `Previews` class (public modifier)

2021-01-05 16:58 UTC, bitwiseman commented
Hm, I thought I'd seen Mockito work on internal classes, but ... oh, well. 

@seregamorph 
Do you think it would make sense to move this to an a new sub-package? `org.kohsuke.github.internal` or `org.kohsuke.github.support` or something?

I suppose it is just one class, but there are other classes that might need to be exposed this same way for mocking or even just convenience. For example, it probably makes sense to move the `Preview` annotation in there as well. There is no reason for any client of this library to use or need to know about that annotation.

2021-01-05 18:40 UTC, bitwiseman requested changes
Thanks for the PR!

I understand this blocks adoption of 1.118 for you due to test breakage. 

I'd like to resolve the question I asked about package placement before merging, but once that is done, I'm happy to merge and release this quickly.

2021-01-05 20:13 UTC, seregamorph commented
@bitwiseman moved to `internal` sub-package.

2021-01-05 22:38 UTC, bitwiseman approved these changes

2021-01-06 01:23 UTC, merged

2021-01-06 02:16 UTC, bitwiseman commented
@seregamorph 
Released as v1.119.

2021-01-06 07:35 UTC, seregamorph commented
Thanks

2021-01-06 20:39 UTC, youming-lin commented
Thanks for the fix! I hit the same issue and eventually realized that the enum not being visible is the cause.

Prior to this change it seemed odd that a function that returns instance of `Previews[]` type is public but `Previews` itself was not. If this type is not meant to be exposed outside the package, then perhaps the function should've also been default instead of public visibility.