upgrade commons-io due to CVE-2021-29425
hub4j/github-api pull request #1124
Opened 2021-04-21 09:48 UTC by alexanderkjall

# Description

Upgrade commons-io to 2.8.0, it's a vulnerability in FileNameUtils.normalize that isn't used in this project.

More information about the vulnerability can be found here: https://issues.apache.org/jira/browse/IO-556

I have run the tests locally (which failed to to unrelated javadoc warnings) and done a basic check in my application that uses github-api, but not done any other testing.

2021-04-21 15:19 UTC, bitwiseman requested changes
This project is used by other projects that have pinned a lower version of `commons-io`. 
I think it makes sense for use to upgrade the version we use by default but we need to enforce only using methods that are compatible with lower versions.  Please add a test to [ArchTests.java](https://github.com/hub4j/github-api/blob/main/src/test/java/org/kohsuke/github/ArchTests.java) that checks that we are only using a specified approved list for methods from `commons-io`.

2021-04-21 18:15 UTC, bitwiseman commented
As noted, this library does not use the method effected by this CVE so it is not urgent to merge and release.

2021-04-26 12:21 UTC, alexanderkjall commented
I looked a bit on ArchTests and to be honest I don't understand how to write a unit test that would fail if a function that's not in the library version 2.4 is used?

2021-04-27 04:19 UTC, bitwiseman commented
@alexanderkjall 
It's easy! You just... 
Wait, no, I mean, ArchUnit is pretty friendly, you can...

Oh, well, it looks like the test I wrote to enforce using `assertThat()` during tests was wrong. 

Also, checking the methods is not at all intuitive and the documentation for this scenario is not helpful.  

So, thanks for asking. I've implemented a minimal test that does not ensure non-breakage, but will force people to consider when that add commons method calls.

2021-04-27 22:28 UTC, bitwiseman approved these changes

2021-04-28 18:35 UTC, bitwiseman commented
@gsmet @alexanderkjall 
Could you review these changes?

2021-04-28 18:48 UTC, gsmet requested changes
Spotted a few minor things.

I'm not very familiar with ArchUnit but I suppose you have tested adding another method fails the build?

2021-04-28 18:48 UTC, gsmet commented on src/test/java/org/kohsuke/github/ArchTests.java
> +        final ArchRule onlyApprovedApacheCommonsLang3Methods = classes()
```suggestion
        final ArchRule onlyApprovedApacheCommonsMethods = classes()
```
`IOUtils` is in commons-io.

2021-04-28 18:48 UTC, gsmet commented on src/test/java/org/kohsuke/github/ArchTests.java
> +                        "Commons methods must be manually verified to be compatible with commons-io:2.4 or earlier and commons-lang3:3.9 or earlier should be used.");
```suggestion
                        "Commons methods must be manually verified to be compatible with commons-io:2.4 or earlier and commons-lang3:3.9 or earlier.");
```

2021-04-28 18:48 UTC, gsmet commented on src/test/java/org/kohsuke/github/ArchTests.java
> +        onlyApprovedApacheCommonsLang3Methods.check(classFiles);
```suggestion
        onlyApprovedApacheCommonsMethods.check(classFiles);
```

2021-04-28 20:34 UTC, bitwiseman commented
@gsmet  Yes, I've verified that methods not on the list are caught by the test.

2021-04-29 15:41 UTC, merged

2021-05-19 15:00 UTC, jeffalder commented
@bitwiseman - Is it possible to get a release cut that includes this PR? I'd be interested in upgrading to make the CVE go away.

2021-05-24 12:12 UTC, bitwiseman commented
@jeffalder Done.