(refactor) Replace complex parsing logic from GHEvent.type to GHEvent with static mapping
hub4j/github-api pull request #1126
Opened 2021-04-21 12:15 UTC by akashRindhe

https://github.com/hub4j/github-api/issues/1099

# Description

Replace complex parsing logic from GHEvent.type to GHEvent with static mapping

2021-04-21 15:48 UTC, bitwiseman requested changes
This is not what I was expecting, but it works, is clearer, and it has to be faster than the old way. 

Minor changes needed.

2021-04-21 15:48 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHEvent.java
> +    public enum GitHubEventType {
I don't think this needs to be public.  It is only used like an private`HashMap<String, GHEvent>`.  
```suggestion
    enum GitHubEventType {
```

2021-04-21 15:48 UTC, bitwiseman commented on src/test/java/org/kohsuke/github/GHEventTest.java
> +    public void regressionTest() {
Add a test for the `GHEvent.UNKNOWN` behavior.

2021-04-21 18:42 UTC, bitwiseman reviewed
If you use EnumUtils t hat would be better.

2021-04-21 18:42 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHEvent.java
> +        WatchEvent(WATCH);
```suggestion
        WatchEvent(WATCH),
        Unknown(UNKNOWN);
```

2021-04-21 18:42 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHEvent.java
> +                return UNKNOWN;
```suggestion
            // import static org.kohsuke.github.internal.EnumUtils;
            GitHubEventType gitHubEventType = EnumUtils.getNullableEnumOrDefault(GitHubEventType.class, event, Unknown);                     
            return gitHubEventType.event;
```

2021-04-22 01:57 UTC, akashRindhe commented
Thanks for making the changes. I believe everything is resolved now and is good to merge?

2021-04-22 06:53 UTC, merged

2021-04-22 18:12 UTC, bitwiseman commented
@akashRindhe 
FYI, I'm sure you could have made the changes yourself, but I felt like getting them done while I was looking at them.   Hope you don't mind.  Thanks for your contributions.

2021-04-22 23:36 UTC, akashRindhe commented
> @akashRindhe
> FYI, I'm sure you could have made the changes yourself, but I felt like getting them done while I was looking at them. Hope you don't mind. Thanks for your contributions.

No issues mate. Cheers :)