(feat) Support code-scanning API (Pt#1)
hub4j/github-api pull request #1142
Opened 2021-05-19 14:06 UTC by akashRindhe

# Description

Related issue - https://github.com/hub4j/github-api/issues/1133
New feature supporting GitHub code-scanning API. 

As this is a big feature with multiple functions, breaking this into smaller PRs to reduce review effort. The functions supported in this PR are -

- [Listing all code-scanning alerts for a repository](https://docs.github.com/en/rest/reference/code-scanning#list-code-scanning-alerts-for-a-repository)
- [Get a code-scanning alert for a repository by its id](https://docs.github.com/en/rest/reference/code-scanning#get-a-code-scanning-alert)
- [List all instances for a code-scanning alert](https://docs.github.com/en/rest/reference/code-scanning#list-instances-of-a-code-scanning-alert)

2021-05-28 07:56 UTC, bitwiseman commented
@akashRindhe 
We value contributions like this.  I apologize for the delay reviewing and merging.  We've seen some high priority issues come in and I personally have other work I've needed to focus on.  I will get to this as soon as I can.

2021-05-28 07:59 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHCodeScanningAlert.java
> +        return most_recent_instance;
@akashRindhe 
This is marked as not covered.  Please see if there's anything you can do to cover this method and any other methods that are not covered by tests.  Don't wear yourself out on it, but just take another look and see if any of them are easy cover.

2021-06-01 23:20 UTC, bitwiseman requested changes
Please review all messages regarding lines not covered from code coverage and fix or comment on why they are not covered.

2021-09-24 06:45 UTC, bitwiseman commented
@ravingbool 
Do you think you could do the testing to get this in shape to merge?  (You reacted 👍 above, so I thought it might be of interest to you.)

2021-11-23 18:02 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHRepository.java
> +    }
There are other filters: 
https://docs.github.com/en/rest/reference/code-scanning#list-code-scanning-alerts-for-a-repository

These filters can be combined so having only single filter method available doesn't seem right.

2021-11-28 18:42 UTC, bitwiseman commented
Converted to Draft as it is not ready for review.

2022-04-06 15:48 UTC, jgangemi commented
hey @bitwiseman / @akashRindhe where does this stand? i could use this functionality at the day job and am happy to pick up on it.

2022-04-07 04:57 UTC, bitwiseman commented
> hey @bitwiseman / @akashRindhe where does this stand? i could use this functionality at the day job and am happy to pick up on it.

What's needed is a review of all messages regarding lines not covered from code coverage and fix or comment on why they are not covered.

2022-04-07 14:05 UTC, jgangemi commented
ok - i've created a new branch to work on. i'll push something up for some initial feedback.

2022-04-08 03:27 UTC, bitwiseman commented
> ok - i've created a new branch to work on. i'll push something up for some initial feedback.

Just open a new PR. That will get you all the checking behavior that you're going to need.  Just keep @akashRindhe's original commits and build on top of them. That way they still get the credit for their work when the PR is merged.

2023-10-20 20:58 UTC, closed without merging