Fix issues related to introduction of new values in GHEvent
hub4j/github-api pull request #1159
Opened 2021-05-27 09:40 UTC by gsmet

@bitwiseman I decided to apply the same strategy we used for other things: use Strings for serialization/deserialization and only switch to enums for APIs. It's a bit less optimal but less risky. Another better option would be to have custom Jackson deserializer but that's probably something we need to keep for 2.0.

I also fixed an inconsistency in `EnumUtils`: one method was user uppercase values and not the other. This is a recipe for disaster.

Better reviewed commit per commit as I kept them semantic.

I'm not exactly sure if it's worth adding tests as we would have to add tests with unknown values for each enum all over the place.

Fixes #1156

2021-05-27 11:06 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/internal/EnumUtils.java
> +            return Enum.valueOf(enumClass, value.toUpperCase(Locale.ROOT));
I actually don't want to do this.  The values are case-sensitive on purpose.  I'm open to discussing changing this but not as part of this PR.

2021-05-27 11:09 UTC, bitwiseman requested changes
The case sensitivity is intentional.

2021-05-27 11:13 UTC, gsmet commented
Mkay. My big concern is that we have two nearly identical methods and the nullable behavior should be the only difference between the two.

I don't mind how we fix it but I think we need to make the methods consistent in one way or another.

I will remove this commit from the PR.

2021-05-27 11:32 UTC, bitwiseman commented
@gsmet 
 You are completely correct in principle, and I'm almost sure you're right in this case.  

I think the reason I chose to do it that way was to match the exiting method's behavior (which was case-sensitive). The events area is not well tested, so I would like to err on the side of caution.  Perhaps not it as an issue and link to https://github.com/hub4j/github-api/pull/1159/commits/38460dc8a9703feac2c6132d49b0d0c160864955 and we can come back to it?

2021-05-27 11:44 UTC, gsmet commented
OK, I removed this commit and did the case change at the call sites.

2021-06-01 08:04 UTC, hcoles commented
Is there anything I can do to help get this merged?

2021-06-01 16:54 UTC, sathishavm commented
I like this change needs to be merged

2021-06-01 23:13 UTC, merged