Add getAppInstallations(/user/installations) method on GHMyself
hub4j/github-api pull request #1187
Opened 2021-06-21 21:26 UTC by t0m4uk1991

# Description

Add  getAppInstallations (under the hood call on /user/installations) method in GHMyself

For more info pls take a look at https://docs.github.com/en/rest/reference/apps#list-app-installations-accessible-to-the-user-access-token

2021-06-21 22:09 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallations.java
> +    private int totalCount;
This is done automatically by Jackson. 
```suggestion
    private int totalCount;
```

2021-06-21 22:26 UTC, bitwiseman requested changes
You've tested this for 1 installation and it works fine, but ...

This is actually a paged response.  Similar to search and a number of other endpoints
https://docs.github.com/en/rest/reference/apps#list-app-installations-accessible-to-the-user-access-token--parameters
😭 

You'll need to implement this using a class extending `PagedIterable` in about the same way   https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/PagedSearchIterable.java does.

2021-06-22 17:24 UTC, t0m4uk1991 commented
Hi @bitwiseman 

Thanks for quick feedback.
I updated PR, could you please take a look again?

2021-06-22 19:07 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallationsPage.java
> +        return total_count;
Test this.

2021-06-22 19:08 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
> +    }
Don't think you need this now. `root` gets bound by Jackson automatically.

2021-06-22 19:37 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallationsPage.java
> +    }
```suggestion
    GHAppInstallation[] getInstallations() {
        return installations;
    }
```

2021-06-22 19:38 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
> +    }
```suggestion
```

I don't think you need this now. `root` gets bound by Jackson automatically. 

https://github.com/hub4j/github-api/blob/81f23e8ae51218b63001c10077a016f07093deae/src/main/java/org/kohsuke/github/GitHubInteractiveObject.java#L13-L14

2021-06-22 19:38 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallationsIterable.java
> +                return v.getInstallations(root);
```suggestion
                return v.getInstallations();
```

2021-06-22 19:39 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
> +    }
Also if needed there's already a `wrapUp()` on line 313.

2021-06-22 19:51 UTC, bitwiseman approved these changes

2021-06-22 19:52 UTC, merged