Applied Refactoring
hub4j/github-api pull request #1638
Opened 2023-04-06 13:49 UTC by BadhriNadh

# Description

1. Variable 'v' does not have any meaning. So, renamed as 'includeReadNotifications',  'restrictedToParticipatingNotifications' and  ‘pollIntervalHeaderValue’.
2. Extracted a block to new method named 'getLatestUnReturnedThread',
3. Extracted a block to new method named 'waitUntilNextPollingTime'
4. Extracted a block to new method named 'updateThreadsAndMetadataFromGitHub'
5. Moved condition to a function that returns a boolean.
6. The ‘hashcode’ method in this class hierarchy [GHUser -> GHRepository] is overridden in a subclass and is only utilized in that subclass without being used in any other classes in the hierarchy. Therefore, the implementation of the hashcode method has been moved down to the subclass where it is actually used to simplify the parent class and make the code more modular.
7. The ‘getApiRoute’ method was present in multiple subclasses, but with slight implementation differences. To address this, I used the Template Method pattern and pulled-up the method to the parent class. This eliminated code duplication, simplified the codebase, and made it easier to maintain and update the common code. <--This is fixing a potential issue-->
8. Method ‘getApiTail’ has almost the same implementation in four classes: GHBlobBuilder, GHCommitBuilder, GHCommitComment, and GHTreeBuilder. It's also causing feature envy smell with GHRepository so moved these methods to GHRepository into one method. <--This is fixing a potential issue-->

# Before submitting a PR:

- [ ] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Add JavaDocs and other comments as appropriate. Consider including links in comments to relevant documentation on https://docs.github.com/en/rest .  
- [ ] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [ ] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [ ] Fill in the "Description" above with clear summary of the changes. This includes:
  - [ ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [ ] Enable "Allow edits from maintainers".

2023-04-14 16:53 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHObject.java
> +    public String getApiRoute(GHRepository owner) {
```suggestion
    protected String getApiRoute(GHRepository owner) {
```

2023-04-14 17:02 UTC, bitwiseman requested changes
Generally approve of these refactors.  Some questions/requests.

2023-04-14 17:02 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHArtifact.java
> +    protected String getApiRouteImpl() {
I don't love this `*Impl` pattern, but it makes sense here.

2023-04-21 23:49 UTC, BadhriNadh commented
Need a different approach for this api

2023-04-21 23:49 UTC, closed without merging