Allowed creation of PR review comments using line number. Fixes #1645
hub4j/github-api pull request #1649
Opened 2023-04-30 12:46 UTC by AlkahtaniHisham

# Description

Updated org.kohsuke.github.GHPullRequestReviewBuilder to allow creating pull request review comments by line, instead of the deprecated parameter position.

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments as appropriate. Consider including links in comments to relevant documentation on https://docs.github.com/en/rest .  
- [ ] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [x] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

2023-04-30 14:21 UTC, alexec reviewed
I think you’ll need to support both line number and position, for backwards compatibility.

They can both be nullable. So change `position` to be `Integer` and overload the `comment` method with a version that takes both `position` and `line`. 

That said, it might be good to support `start_line` and `side` too. This allows for richer multi-line comments.


https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request

2023-04-30 16:34 UTC, AlkahtaniHisham commented
Github api says
> If you use position, the line, side, start_line, and start_side parameters are not required.

2023-04-30 16:36 UTC, AlkahtaniHisham commented
github docs say
> If you use position, the line, side, start_line, and start_side parameters are not required. 
so would it work if I keep the old method (with `position`) unchanged, and add a method that accepts `line`, `start_line`, and `side`?

2023-04-30 23:32 UTC, alexec commented
yes, that'd work

2023-05-01 13:53 UTC, alexec approved these changes
LGTM

2023-05-04 16:50 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHPullRequestReviewBuilder.java
> +     *            The position in the diff where you want to add a review comment. Note this value is not the same as
Instead of saying what this is not, describe what it is.

2023-05-04 16:52 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHPullRequestReviewBuilder.java
> +        DraftReviewComment(String body, String path, Integer position) {
For this constructor, the `position` is required and not allowed to be `null`, correct? 
```suggestion
        DraftReviewComment(String body, String path, int position) {
```

2023-05-04 16:54 UTC, bitwiseman requested changes
Looks reasonable, minor suggestions. 
Add tests to exercise the new method.

2023-05-06 18:57 UTC, bitwiseman commented on src/test/java/org/kohsuke/github/GHPullRequestTest.java
> +                .comment("other niggle", "README.md", 1, null, null)
You'll need to update the test data for these new interactions.

2023-05-14 17:31 UTC, alexec approved these changes
Was there some kind of merge conflict with all the `.json` files?

I never said this, but the use case I have is making multi line suggestions.

2023-06-30 20:00 UTC, bitwiseman commented
@alexec @AlkahtaniHisham 
Could you record new test data?

2023-07-14 11:52 UTC, alexec commented
LGTM

2023-07-17 16:39 UTC, bitwiseman commented
@AlkahtaniHisham We need new test data.

2023-08-09 17:18 UTC, gilday commented
@bitwiseman I can help record the test data if needed. I understand I would need access to hub4j-test-org to record and check-in interactions with that account.

2023-08-14 19:43 UTC, bitwiseman commented
@gilday Invitation sent for the test org.

2023-10-15 05:30 UTC, closed without merging