Re-Prepare request for every retry
hub4j/github-api pull request #1680
Opened 2023-06-27 12:24 UTC by emrebasar

# Description

Currently, a retried request fails if the authentication token expires between retries. This can be a common experience, as GitHub API can throttle a user for up to an hour, which is longer than the lifetime of an authentication token retrieved via the GitHub Application Installation.

This change ensures that a recent token is used in each request by re-creating the connector request for every retry.

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments explaining the behavior. 
- [x] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [x] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [x] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [x] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

2023-06-30 19:55 UTC, bitwiseman commented
@emrebasar 
I see what you're saying, this is probably an acceptable change, but you'll at least need to update tests to match the new behavior. 

Also, retry scenarios tend to be quick turnaround.  What you're talking about is generally only going to happen related to rate limiting and long waits. Maybe you should add special error scenario for case you want to address.  Make it similar to https://github.com/hub4j/github-api/blob/c4948917ca9fbeee190bcddf0d12941472dff03d/src/main/java/org/kohsuke/github/GitHubClient.java#L629-L653 where you detect the situation and throw a `RetryRequestException`.  

The detector should check the http error code and prepare a new request.  If the authorization string for new request is the same as the current connectorRequest, then you have a valid failure. Otherwise,  throw a `RetryRequestException` with the updated `GitHubConnectorRequest` that the main loop will use for retry.  

Make sense?

2023-06-30 19:56 UTC, bitwiseman requested changes
For most users, preparing the request again is not needed. As noted, we should detect the scenario you describe an update the request only in that case.

2023-07-03 06:07 UTC, emrebasar commented
Thank you for the feedback. In our use case, rate limiting is the primary cause of retries, and we observe this specific scenario fairly often, though I agree that it might not be the case for majority of the use cases. I will update the code accordingly, and fix the failing tests.

2023-07-04 00:19 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GitHubClient.java
> +    private void detectExpiredToken(GitHubConnectorResponse connectorResponse, GitHubRequest request)
This looks great.

2023-07-04 04:44 UTC, bitwiseman requested changes
All we need now is a test covering the newly added code.

2023-07-07 12:23 UTC, emrebasar commented
Hi @bitwiseman, I did dive into this, and tried implementing some tests but got stuck at configuring the correct Wiremock behavior. I am planning to continue looking at this, beginning Week 32. How would you like to proceed? Should we close this PR, and open a new one when tests are fixed, or should we keep this one open?

2023-07-13 07:06 UTC, bitwiseman commented
@emrebasar 
Take your time, we'll keep this open. Update this PR as needed.  Thanks for working on this.  Feel free to ask questions if you get stuck.

2023-08-15 19:12 UTC, bitwiseman commented
Missed javadoc comments on tests.

2023-08-15 21:26 UTC, merged