Add Suspended Installation Properties to GHAppInstallation
hub4j/github-api pull request #1780
Opened 2024-01-15 18:15 UTC by gilday

# Description

A suspended app installation has `suspended_at` and `suspended_by` properties that were missing from the `GHAppInstallation` class.

https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installations-for-the-authenticated-app

2024-01-15 18:19 UTC, gilday commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
These properties are represented in the current test data, but they are always `null`. To record examples of suspended installations, it's my understanding that a test would need to suspend an installation on the hub4j-test-org, and doing so requires admin level access to the org. This sounds prohibitively difficult to contribute. Please advise if there's a good way to test these changes.

2024-01-25 23:43 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
You could manually add test datafiles or I can grant you admin access to the org, whichever you would rather do.

2024-01-25 23:45 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
> +    @JsonProperty("suspended_at")
This is conversion in done automatically. 

```suggestion
```

2024-01-25 23:46 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
> +    private GHUser suspendedBy;
This is conversion in done automatically. 

```suggestion
```
This is conversion in done automatically. 

```suggestion
```
This conversion is done automatically. 
```suggestion
    private Date suspendedAt;
    private GHUser suspendedBy;
```

2024-01-25 23:49 UTC, bitwiseman requested changes
I understand that adding tests for fields like these is difficult, but they need to be covered.  If they aren't a future change could silent break this functionality.

2024-02-26 03:24 UTC, gilday commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
Added the tests and test files.

2024-03-08 22:36 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
> +    }
```suggestion
    public Date getSuspendedAt() {
        return GitHubClient.parseDate(suspendedAt);
    }
```

2024-03-08 22:36 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHAppInstallation.java
> +    private Date suspendedAt;
```suggestion
    private String suspendedAt;
```

2024-03-08 22:55 UTC, merged