Add listContributors method parameter to determine whether to include…
hub4j/github-api pull request #1907
Opened 2024-08-09 21:07 UTC by augustd

… anonymous contributors.

Fixes #1905

# Description

# Before submitting a PR:

- [ X] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [X ] Add JavaDocs and other comments explaining the behavior. 
- [X ] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [ X] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [X ] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [ ] Fill in the "Description" above with clear summary of the changes. This includes:
  - [ ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [ ] Enable "Allow edits from maintainers".

2024-09-06 16:15 UTC, bitwiseman requested changes
Please fix CI failures

2024-09-06 16:18 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHRepository.java
>          return root().createRequest().withUrlPath(getApiTailUrl("contributors")).toIterable(Contributor[].class, null);
```suggestion
        return listContributors(null);
```

2024-09-06 16:21 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHRepository.java
> +        return listContributors();
```suggestion
        return root().createRequest()
                .withUrlPath(getApiTailUrl("contributors"))
                .with("anon", includeAnonymous)
                .toIterable(Contributor[].class, null);
```

2024-09-06 16:25 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHRepository.java
> +        return listContributors();
```suggestion
    public PagedIterable<Contributor> listContributors(Boolean includeAnonymous) throws IOException {
        return root().createRequest()
                .withUrlPath(getApiTailUrl("contributors"))
                .with("anon", includeAnonymous)
                .toIterable(Contributor[].class, null);
```

2024-11-15 01:49 UTC, augustd commented
@bitwiseman I've incorporated the changes you requested and all tests now pass. Can this be merged and released?

2025-01-06 17:07 UTC, bitwiseman approved these changes

2025-01-06 17:08 UTC, merged

2025-01-07 02:16 UTC, bitwiseman commented
I'll get to it this week.