fix GitHub notification interface return "Unable to parse If-Modified…
hub4j/github-api pull request #1984
Opened 2024-11-12 12:39 UTC by AsherSu

…-Since request header"

# Description

fix GitHub notification interface return "Unable to parse If-Modified-Since request header"

# Before submitting a PR:

- [ ] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Add JavaDocs and other comments explaining the behavior. 
- [ ] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [ ] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [ ] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [ ] Fill in the "Description" above with clear summary of the changes. This includes:
  - [ ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [ ] Enable "Allow edits from maintainers".

2024-11-17 22:51 UTC, bitwiseman commented
@AsherSu  Need test that covers this branch.

2024-11-17 22:54 UTC, bitwiseman requested changes
This looks reasonable.  Need to update the test to cover this path.

2024-11-20 15:58 UTC, AsherSu commented
@bitwiseman The test cases have been reviewed and approved, are they satisfactory?

2024-11-21 03:57 UTC, bitwiseman approved these changes

2024-11-21 03:58 UTC, merged