Implement deployment API support for ant-man and flash previews
hub4j/github-api pull request #960
Opened 2020-10-02 20:11 UTC by marcoferrer

# Description 
* Implement deployment API support for ant-man and flash previews.
* This pr includes two new constants in the `Previews` class. 
* Getters for newly introduced fields are added to `GHDeployment` and `GHDeploymentStatus`.
* New builder setters are implemented for `GHDeploymentBuilder` and `GHDeploymentStatusBuilder`.
* `GHDeploymentState` has been updated to support `in_progress`, `queued`, and `inactive`. 
  * [Related Gh API Docs](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-deployment-status)
* Marked `GHDeploymentStatus.getTargetUrl()` and `GHDeploymentStatusBuilder.targetUrl()` as `@Deprecated`.
  * Method documentation has been updated with to notify users to replace usages with `logUrl()` where appropriate

# Before submitting a PR:
We love getting PRs, but we hate asking people for the same basic changes every time. 

- [X] Push your changes to a branch other than `master`. Create your PR from that branch.    
- [X] Add JavaDocs and other comments
- [ ] Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.
- [ ] Run `mvn clean compile` locally. This may reformat your code, commit those changes.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.

# When creating a PR: 

- [X] Fill in the "Description" above. 
- [X] Enable "Allow edits from maintainers".

2020-10-05 22:06 UTC, marcoferrer commented
@bitwiseman Tests are implemented and this is ready for review. One change that I wanted feedback on was the addition of a value field to the `Preview` annotation. Thx

2020-10-21 20:52 UTC, marcoferrer commented
@bitwiseman friendly bump

2020-11-03 20:47 UTC, bitwiseman requested changes
Sorry for long delay. 

Only one type of change needed.  Otherwise looks great.

2020-11-03 20:47 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/Preview.java
> +
Very nice.  I'd almost prefer it to not be optional but I see why it needs to be.

2020-11-03 20:47 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHDeployment.java
> +    @Preview(Previews.FLASH)
We mark preview fields as `@Deprecated` to make sure end users are aware (via editor feedback) that they are not stable APIs. 

This comment applies to all usages. 

```suggestion
    @Deprecated
    @Preview(Previews.FLASH)
```

2020-11-23 22:17 UTC, marcoferrer commented
@bitwiseman Feedback addressed. `@Deprecated` has been added to applicable targets.

2020-11-25 14:17 UTC, bitwiseman approved these changes

2020-11-25 14:17 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/Preview.java
> + * signify that the deprecation is required until preview feature being used is promoted to stable.
👍

2020-11-25 14:37 UTC, merged