pull_request action "edited": changes
hub4j/github-api pull request #979
Opened 2020-11-18 18:14 UTC by seregamorph

# Description 
** Describe your change here**
Webhook with `X-GitHub-Event: pull_request` and `"action": "edited"` has a field `"changes"` that is not present in `GHEventPayload.PullRequest`. I've found three triggers that leads to "edited" action:
- Change PR title:
```json
...
  "changes": {
    "title": {
      "from": "REST-276 - easy-random"
    }
  },
...
```
(other fields are omitted)
- Change PR description:
```json
...
"changes": {
    "body": {
      "from": "**JIRA Ticket URL:**\r\nhttps://jira.devfactory.com/browse/REST-276\r\n\r\n..."
    }
  },
...
```
- Change target branch:
```json
...
  "changes": {
    "base": {
      "ref": {
        "from": "develop"
      },
      "sha": {
        "from": "4b0f3b9fd582b071652ccfccd10bfc8c143cff96"
      }
    }
  },
...
```

So, `"changes"` fields contain old value that was changed, while `pull_request` object has latest values (see UT json payloads)

# Before submitting a PR:
We love getting PRs, but we hate asking people for the same basic changes every time. 

- [ ] Push your changes to a branch other than `master`. Create your PR from that branch.    
- [ ] Add JavaDocs and other comments
- [ ] Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.
- [ ] Run `mvn clean compile` locally. This may reformat your code, commit those changes.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.

# When creating a PR: 

- [ ] Fill in the "Description" above. 
- [ ] Enable "Allow edits from maintainers".

2020-11-18 18:15 UTC, seregamorph commented on src/main/java/org/kohsuke/github/GHPullRequestChanges.java
> +    private GHCommitPointer base;
`base` changed - covered with UT
`title` changed - covered with UT
`body` changed - cover on demand

2020-11-18 18:16 UTC, seregamorph commented on src/test/java/org/kohsuke/github/GHEventPayloadTest.java
> +        assertThat(event.getPullRequest().getBody(), startsWith("**JIRA Ticket URL:**"));
body not changed - hence `"changes"` does not contain it

2020-11-18 20:31 UTC, bitwiseman requested changes
Minor changes to test.

2020-11-18 20:31 UTC, bitwiseman commented on src/test/java/org/kohsuke/github/GHEventPayloadTest.java
> +        assertThat(event.getChanges().getBody(), nullValue());
```suggestion
        assertThat(event.getChanges().getBody(), nullValue());
        assertThat(event.getChanges().getTitle(), nullValue());
```

2020-11-18 20:31 UTC, bitwiseman commented on src/test/java/org/kohsuke/github/GHEventPayloadTest.java
> +        assertThat(event.getChanges().getBody(), nullValue());
```suggestion
        assertThat(event.getChanges().getBody(), nullValue());
        assertThat(event.getChanges(). getChanges(), nullValue());
```

2020-11-18 20:48 UTC, bitwiseman commented on src/test/java/org/kohsuke/github/GHEventPayloadTest.java
> +        assertThat(event.getChanges(). getChanges(), nullValue());
```suggestion
        assertThat(event.getChanges().getTitle(), nullValue());
```

2020-11-18 20:50 UTC, bitwiseman commented on src/test/java/org/kohsuke/github/GHEventPayloadTest.java
> +        assertThat(event.getChanges(). getChanges(), nullValue());
```suggestion
```

2020-11-18 20:50 UTC, bitwiseman commented on src/test/java/org/kohsuke/github/GHEventPayloadTest.java
> +        assertThat(event.getChanges().getTitle(), nullValue());
```suggestion
```

2020-11-19 11:05 UTC, seregamorph commented
@bitwiseman not sure what changes did you expect. My logic was: for three fields: `title`, `body` and `base` check old value (in `"changes"` field) and current value (in `"pull_request` field). There is a small test enhancement.

2020-11-24 02:26 UTC, bitwiseman approved these changes

2020-11-24 02:26 UTC, merged