Feature/add update hook
hub4j/github-api pull request #982
Opened 2020-11-20 14:47 UTC by mronus

# Description 

* Add support for updating hooks
* Fix the type of parameter in `getRepositoryById`
* Replace `position` with `line` in `createReviewComment` in order to avoid position computation

2020-11-24 15:04 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GitHub.java
> +    public GHRepository getRepositoryById(long id) throws IOException {
Please make this a separate PR and keep the existing method but make it deprecated. 
Also, add tests for both the old and new methods.  Thanks!

2020-11-24 15:12 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHPullRequest.java
> +                .with("line", position)
This too needs to be a separate PR, with tests for the change.

The docs indicate that `position` and `line` are not equivalent. You'll probably need to implement a builder to support the various parameter combinations.
https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#create-a-review-comment-for-a-pull-request

2020-11-24 15:19 UTC, bitwiseman commented on src/main/java/org/kohsuke/github/GHHooks.java
> +                    .method("PATCH")
Does `POST` not work?

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-webhook

2020-11-24 15:26 UTC, bitwiseman requested changes
Thank you for choosing to contribute!  
Please split these three independent changes into separate PRs and add tests.  Thanks!

2020-12-21 18:22 UTC, bitwiseman commented
@mronus  
Do you have time to finish working on this?

2020-12-21 21:06 UTC, mronus commented
@bitwiseman I don't know when I can finish it but will try to do it asap, like in a few weeks at the latest.

2021-01-03 12:57 UTC, mronus commented
This PR got closed as it was split into 3 different PRs.

2021-01-03 12:57 UTC, closed without merging